# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  PROJECT_SOLUTION: "./TrashService.sln"
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      working-directory: .
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        dotnet-quality: 'qa'

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_SOLUTION }}
    - name: Build
      run: dotnet build ${{ env.PROJECT_SOLUTION }} --no-restore 
