name: Build and deploy .NET application to container app trashservice-app-20250327091128
on:
  push:
    branches:
      - main
env:
  CONTAINER_APP_CONTAINER_NAME: trashservice
  CONTAINER_APP_NAME: trashservice-app-20250327091128
  CONTAINER_APP_RESOURCE_GROUP_NAME: rg-trash-service
  CONTAINER_REGISTRY_LOGIN_SERVER: trashservice20250327091758.azurecr.io
  DOCKER_FILE_PATH: src/TrashService/Dockerfile
  PROJECT_NAME_FOR_DOCKER: trashservice
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.TrashService20250327091758_USERNAME_EF66 }}
          password: ${{ secrets.TrashService20250327091758_PASSWORD_EF66 }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
          file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to containerapp
        uses: azure/CLI@v2
        with:
          inlineScript: >
            az config set extension.use_dynamic_install=yes_without_prompt

            az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.TrashService20250327091758_USERNAME_EF66 }} --password ${{ secrets.TrashService20250327091758_PASSWORD_EF66 }}

            az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
      - name: logout
        run: >
          az logout
